import { t, type Dictionary } from "intlayer";

const pageContent = {
    key: "terms-page",
    content: {
        title: t({
            en: "Terms & Conditions",
            tr: "Şartlar ve Koşullar",
            de: "Nutzungsbedingungen"
        }),
        text: t({
            en: "Effective Date: 28 September 2024\n\nWelcome to Touch Sensei! By downloading or using our mobile application, you agree to comply with and be bound by the following Terms and Conditions. If you do not agree with these terms, please do not use the app.\n\n1. Acceptance of Terms\n\nBy accessing or using Touch Sensei, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.\n\n2. Use of the App\n\nTouch Sensei is designed for personal, non-commercial use. You may not use the app for any unlawful purpose or in any way that may damage or impair the app or interfere with any other user’s use of the app.\n\n3. Intellectual Property Rights\n\nAll content, trademarks, and other intellectual property rights in the app, including background images created using Microsoft’s Designer AI solution, are owned by or licensed to Touch Sensei. You are granted a limited, non-exclusive, and non-transferable license to use the app for personal, non-commercial purposes.\n\n4. No Data Collection\n\nTouch Sensei does not collect, store, or share any personal information from its users. Your privacy is important to us, and we are committed to providing a safe and secure experience while using our app.\n\n5. Third-Party Services\n\nTouch Sensei does not integrate or utilize any third-party services that collect or process your personal information. Our app operates independently without any external data sharing.\n\n6. Disclaimers\n\nThe app is provided 'as is' and 'as available' without any warranties of any kind. Touch Sensei does not guarantee that the app will be uninterrupted, error-free, or free from viruses or other harmful components.\n\n7. Limitation of Liability\n\nTo the fullest extent permitted by law, Touch Sensei shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of or inability to use the app.\n\n8. Changes to Terms\n\nWe may update these Terms and Conditions from time to time. You are advised to review these terms periodically for any changes. Changes are effective when they are posted within the app.\n\n9. Contact Us\n\nIf you have any questions or concerns about these Terms and Conditions, please contact us at:\n",
            tr: "Geçerlilik Tarihi: 28 Eylül 2024\n\nTouch Sensei'ye hoş geldiniz! Mobil uygulamamızı indirerek veya kullanarak, aşağıdaki Kullanım Şartlarına uymayı kabul etmiş olursunuz. Eğer bu şartlarla aynı fikirde değilseniz, lütfen uygulamayı kullanmayın.\n\n1. Şartların Kabulü\n\nTouch Sensei'ye erişerek veya kullanarak, bu Kullanım Şartlarını okuduğunuzu, anladığınızı ve bu şartlara uymayı kabul ettiğinizi kabul edersiniz.\n\n2. Uygulamanın Kullanımı\n\nTouch Sensei, kişisel ve ticari olmayan kullanım için tasarlanmıştır. Uygulamayı herhangi bir yasadışı amaçla veya uygulamanın zarar görmesine veya etkilenmesine neden olabilecek bir şekilde ya da başka bir kullanıcının uygulamayı kullanımını engelleyecek şekilde kullanamazsınız.\n\n3. Fikri Mülkiyet Hakları\n\nUygulamadaki tüm içerikler, ticari markalar ve diğer fikri mülkiyet hakları, Microsoft'un Designer AI çözümü kullanılarak oluşturulan arka plan görüntüleri dahil olmak üzere, Touch Sensei'ye aittir veya ona lisanslanmıştır. Uygulamayı kişisel, ticari olmayan amaçlarla kullanmanız için sınırlı, münhasır olmayan ve devredilemez bir lisans verilmiştir.\n\n4. Veri Toplanmaması\n\nTouch Sensei, kullanıcılarından herhangi bir kişisel bilgi toplamaz, saklamaz veya paylaşmaz. Gizliliğiniz bizim için önemlidir ve uygulamamızı kullanırken güvenli ve emniyetli bir deneyim sağlamaya kararlıyız.\n\n5. Üçüncü Taraf Hizmetleri\n\nTouch Sensei, kişisel bilgilerinizi toplayan veya işleyen herhangi bir üçüncü taraf hizmeti ile entegre veya bu hizmetleri kullanmaz. Uygulamamız, dış veri paylaşımı olmadan bağımsız olarak çalışmaktadır.\n\n6. Sorumluluk Reddi\n\nUygulama 'olduğu gibi' ve 'mevcut olduğu gibi' herhangi bir garanti olmaksızın sunulmaktadır. Touch Sensei, uygulamanın kesintisiz, hatasız veya virüsler ya da diğer zararlı bileşenlerden arındırılmış olacağını garanti etmez.\n\n7. Sorumluluğun Sınırlandırılması\n\nYasanın izin verdiği en geniş ölçüde, Touch Sensei, uygulamanın kullanımından veya kullanamama durumundan kaynaklanan doğrudan, dolaylı, tesadüfi veya sonuçsal zararlardan sorumlu değildir.\n\n8. Şartlardaki Değişiklikler\n\nBu Kullanım Şartlarını zaman zaman güncelleyebiliriz. Değişiklikler için bu şartları periyodik olarak gözden geçirmenizi öneririz. Değişiklikler, uygulama içinde yayınlandığında geçerlidir.\n\n9. Bizimle İletişime Geçin\n\nBu Kullanım Şartları hakkında herhangi bir sorunuz veya endişeniz varsa, lütfen bizimle iletişime geçin:\n",
            de: "Gültigkeitsdatum: 28. September 2024\n\nWillkommen bei Touch Sensei! Durch das Herunterladen oder die Nutzung unserer mobilen Anwendung stimmen Sie zu, die folgenden Nutzungsbedingungen einzuhalten und sich daran zu halten. Wenn Sie mit diesen Bedingungen nicht einverstanden sind, verwenden Sie bitte die App nicht.\n\n1. Akzeptanz der Bedingungen\n\nDurch den Zugriff auf oder die Nutzung von Touch Sensei erkennen Sie an, dass Sie diese Nutzungsbedingungen gelesen, verstanden haben und an sie gebunden sind.\n\n2. Nutzung der App\n\nTouch Sensei ist für die persönliche, nicht-kommerzielle Nutzung konzipiert. Sie dürfen die App nicht für illegale Zwecke oder auf eine Weise verwenden, die die App beschädigen oder beeinträchtigen oder die Nutzung der App durch andere Benutzer stören könnte.\n\n3. Geistige Eigentumsrechte\n\nAlle Inhalte, Marken und anderen geistigen Eigentumsrechte in der App, einschließlich der Hintergrundbilder, die mit der Microsoft Designer KI-Lösung erstellt wurden, sind im Eigentum von oder lizenziert an Touch Sensei. Ihnen wird eine eingeschränkte, nicht-exklusive und nicht übertragbare Lizenz gewährt, die App für persönliche, nicht-kommerzielle Zwecke zu verwenden.\n\n4. Keine Datenerhebung\n\nTouch Sensei sammelt, speichert oder teilt keine persönlichen Informationen seiner Nutzer. Ihre Privatsphäre ist uns wichtig, und wir setzen uns dafür ein, Ihnen ein sicheres und geschütztes Erlebnis bei der Nutzung unserer App zu bieten.\n\n5. Dienste Dritter\n\nTouch Sensei integriert oder nutzt keine Drittanbieterdienste, die Ihre persönlichen Informationen sammeln oder verarbeiten. Unsere App funktioniert unabhängig und ohne externe Datenweitergabe.\n\n6. Haftungsausschluss\n\nDie App wird 'wie sie ist' und 'wie verfügbar' ohne Gewährleistungen jeglicher Art bereitgestellt. Touch Sensei garantiert nicht, dass die App ununterbrochen, fehlerfrei oder frei von Viren oder anderen schädlichen Komponenten ist.\n\n7. Haftungsbeschränkung\n\nIm größtmöglichen gesetzlich zulässigen Umfang haftet Touch Sensei nicht für direkte, indirekte, zufällige oder Folgeschäden, die aus der Nutzung oder Unfähigkeit zur Nutzung der App entstehen.\n\n8. Änderungen der Bedingungen\n\nWir können diese Nutzungsbedingungen von Zeit zu Zeit aktualisieren. Es wird empfohlen, diese Bedingungen regelmäßig auf Änderungen zu überprüfen. Änderungen treten in Kraft, wenn sie in der App veröffentlicht werden.\n\n9. Kontaktieren Sie uns\n\nWenn Sie Fragen oder Bedenken zu diesen Nutzungsbedingungen haben, kontaktieren Sie uns bitte unter:\n"
        }),
        devWebsite: t({
            en: "Developer's Website",
            tr: "Geliştirici Web Adresi",
            de: "Entwickler-Website"
        }),
        googleForm: t({
            en: "Support Form",
            tr: "Destek Formu",
            de: "Support-Formular"
        })
    },
} satisfies Dictionary;

export default pageContent;
